# Generated by Django 4.0.3 on 2022-03-26 20:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="date of transaction"
            ),
            preserve_default=False,
        ),
    ]
