# Generated by Django 3.2.5 on 2022-06-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
