# Generated by Django 3.2.5 on 2022-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_table_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(default='Tableau', max_length=256),
        ),
    ]
