# Generated by Django 4.0.3 on 2022-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='images/no_photo.jpeg', upload_to='images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
